# Generated by Django 4.2 on 2023-05-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='fecha_creación',
            field=models.DateField(default='2023-05-10'),
        ),
    ]
