# Generated by Django 4.2 on 2023-05-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_alter_ficha_fecha_creación'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='dinero',
            new_name='monto',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fecha_creación',
            field=models.DateField(default='2023-05-11'),
        ),
    ]
