# Generated by Django 4.2 on 2023-05-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0003_rename_dinero_ficha_monto_alter_ficha_fecha_creación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='fecha_creación',
            field=models.DateField(default='2023-05-14'),
        ),
    ]
