# Generated by Django 4.2 on 2023-06-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0005_alter_ficha_fecha_creación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='fecha_creación',
            field=models.DateField(default='2023-06-29'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='monto',
            field=models.CharField(max_length=250),
        ),
    ]
